
import { AppSettings } from '../types';

// Helper for rounded rectangles
function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, width: number, height: number, radius: number) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.lineTo(x + width - radius, y);
  ctx.quadraticCurveTo(x + width, y, x + width, y + radius);
  ctx.lineTo(x + width, y + height - radius);
  ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height);
  ctx.lineTo(x + radius, y + height);
  ctx.quadraticCurveTo(x, y + height, x, y + height - radius);
  ctx.lineTo(x, y + radius);
  ctx.quadraticCurveTo(x, y, x + radius, y);
  ctx.closePath();
}

// Helper for text wrapping
function wrapText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, maxWidth: number, lineHeight: number) {
  const words = text.split(' ');
  let line = '';
  let currentY = y;

  for(let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + ' ';
    const metrics = ctx.measureText(testLine);
    const testWidth = metrics.width;
    if (testWidth > maxWidth && n > 0) {
      ctx.fillText(line, x, currentY);
      line = words[n] + ' ';
      currentY += lineHeight;
    } else {
      line = testLine;
    }
  }
  ctx.fillText(line, x, currentY);
}

// Helper to load image
const loadImage = (url: string): Promise<HTMLImageElement> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "Anonymous";
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = url;
  });
};

// --- SHARED SETUP ---
const setupCanvas = (size: number) => {
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  return { canvas, ctx };
};

const drawBackground = (ctx: CanvasRenderingContext2D, size: number, bgDark: string) => {
  ctx.fillStyle = bgDark;
  ctx.fillRect(0, 0, size, size);

  // Grid Pattern Effect
  ctx.strokeStyle = '#1e293b';
  ctx.lineWidth = 2;
  const gridSize = 60;
  for (let i = 0; i < size; i += gridSize) {
    ctx.beginPath();
    ctx.moveTo(i, 0);
    ctx.lineTo(i, size);
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(0, i);
    ctx.lineTo(size, i);
    ctx.stroke();
  }
};

const drawFromLabel = (ctx: CanvasRenderingContext2D, name: string) => {
  // Enhanced Visibility with slight drop shadow for contrast against grid
  ctx.fillStyle = '#f8fafc'; // White
  ctx.shadowColor = '#000000';
  ctx.shadowBlur = 0;
  ctx.shadowOffsetX = 3;
  ctx.shadowOffsetY = 3;
  
  ctx.font = 'bold 36px "Courier New", monospace'; // Larger font
  ctx.textAlign = 'left';
  ctx.textBaseline = 'top';
  ctx.fillText(`FROM: ${name.toUpperCase()}`, 50, 50);
  
  // Clean up shadow state immediately to prevent ghosting
  ctx.shadowBlur = 0;
  ctx.shadowOffsetX = 0;
  ctx.shadowOffsetY = 0;
  ctx.shadowColor = 'transparent';
};

const drawBranding = (ctx: CanvasRenderingContext2D, size: number) => {
  ctx.font = '24px "Courier New", monospace';
  ctx.fillStyle = '#475569';
  ctx.textAlign = 'center';
  ctx.fillText("GENERATED BY ABHI'S LEDGER", size / 2, size - 40);
};

const drawFooterNameAndId = (ctx: CanvasRenderingContext2D, size: number, y: number, label: string, name: string, id: string, color: string) => {
    ctx.textAlign = 'center';
    
    // Label
    ctx.fillStyle = '#94a3b8'; // Slate 400
    ctx.font = '500 24px "Inter", sans-serif';
    ctx.fillText(label, size / 2, y);

    // Name
    ctx.fillStyle = '#f8fafc'; // White
    ctx.font = 'bold 56px "Inter", sans-serif';
    ctx.fillText(name.toUpperCase(), size / 2, y + 50);

    // ID
    ctx.fillStyle = color; // Accent color or slate
    ctx.font = 'bold 28px "Courier New", monospace';
    ctx.fillText(`ID: ${id}`, size / 2, y + 90);
};

// --- GENERATORS ---

export const generateShareCard = async (
  fromName: string,
  name: string,
  profileId: string,
  amount: number,
  currency: string,
  dueDate: Date | null,
  isOverdue: boolean,
  daysDiff: number,
  customMessage: string
): Promise<File | null> => {
  const size = 1080;
  const { canvas, ctx } = setupCanvas(size);
  if (!ctx) return null;

  const bgDark = '#020617';
  const bgCard = '#0f172a';
  const textLight = '#f8fafc';
  const textDim = '#94a3b8';
  
  let accent = '#10b981';
  let accentDim = 'rgba(16, 185, 129, 0.2)';

  if (isOverdue) {
      accent = '#f43f5e';
      accentDim = 'rgba(244, 63, 94, 0.2)';
  } else if (daysDiff <= 1) {
      accent = '#fbbf24';
      accentDim = 'rgba(251, 191, 36, 0.2)';
  }

  drawBackground(ctx, size, bgDark);
  drawFromLabel(ctx, fromName);

  // MAIN CARD
  const cardMargin = 100;
  const cardWidth = size - (cardMargin * 2);
  const cardHeight = size - (cardMargin * 2) + 20;
  const cardRadius = 40;

  ctx.shadowColor = accent;
  ctx.shadowBlur = 80;
  ctx.shadowOffsetY = 20;
  ctx.fillStyle = bgCard;
  roundRect(ctx, cardMargin, cardMargin, cardWidth, cardHeight, cardRadius);
  ctx.fill();
  
  // CRITICAL FIX: Reset shadow properties to prevent ghosting text
  ctx.shadowBlur = 0;
  ctx.shadowOffsetY = 0;
  ctx.shadowOffsetX = 0;
  ctx.shadowColor = 'transparent';

  ctx.lineWidth = 4;
  ctx.strokeStyle = '#334155';
  ctx.stroke();

  // Accent Line
  ctx.beginPath();
  ctx.moveTo(cardMargin + cardRadius, cardMargin);
  ctx.lineTo(cardMargin + cardWidth - cardRadius, cardMargin);
  ctx.lineWidth = 12;
  ctx.strokeStyle = accent;
  ctx.stroke();

  // Content
  ctx.fillStyle = textDim;
  ctx.font = 'bold 32px "Inter", sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'top';
  ctx.fillText('PAYMENT REQUEST', size / 2, cardMargin + 60);

  ctx.fillStyle = textLight;
  ctx.font = 'bold 140px "Inter", sans-serif'; 
  ctx.textBaseline = 'middle';
  const amountStr = `${currency}${Math.round(amount).toLocaleString('en-IN')}`;
  ctx.fillText(amountStr, size / 2, cardMargin + 200);

  // Status Pill
  let statusText = '';
  if (dueDate) {
      if (isOverdue) {
        statusText = `OVERDUE BY ${daysDiff} DAYS`;
      } else if (daysDiff === 0) {
        statusText = `DUE TODAY`;
      } else {
        statusText = `${daysDiff} DAYS REMAINING`;
      }
  } else {
      statusText = 'NO DEADLINE SET';
  }

  ctx.font = 'bold 36px "Inter", sans-serif';
  const textWidth = ctx.measureText(statusText).width;
  const pillPadding = 40;
  const pillWidth = textWidth + (pillPadding * 2);
  const pillHeight = 70;
  const pillX = (size - pillWidth) / 2;
  const pillY = cardMargin + 300;

  ctx.fillStyle = accentDim;
  roundRect(ctx, pillX, pillY, pillWidth, pillHeight, 20);
  ctx.fill();
  ctx.strokeStyle = accent;
  ctx.lineWidth = 3;
  ctx.stroke();
  ctx.fillStyle = accent;
  ctx.fillText(statusText, size / 2, pillY + pillHeight/2 + 2); 

  // Message
  ctx.fillStyle = '#e2e8f0';
  ctx.font = '500 42px "Inter", sans-serif';
  const messageY = pillY + pillHeight + 80;
  wrapText(ctx, customMessage, size / 2, messageY, cardWidth - 100, 60);

  // Footer
  const bottomSectionY = cardMargin + cardHeight - 160;
  drawFooterNameAndId(ctx, size, bottomSectionY - 20, "ATTN TO:", name, profileId, accent);

  drawBranding(ctx, size);

  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      if (blob) {
        const file = new File([blob], `Payment_Request_${name.replace(/\s/g, '_')}.png`, { type: 'image/png' });
        resolve(file);
      } else {
        resolve(null);
      }
    }, 'image/png');
  });
};

export const generateReceiptCard = async (
  fromName: string,
  payerName: string,
  profileId: string,
  amountPaid: number,
  currency: string,
  timeliness: 'early' | 'ontime' | 'late',
  remainingBalance: number,
  customMessage: string
): Promise<File | null> => {
  const size = 1080;
  const { canvas, ctx } = setupCanvas(size);
  if (!ctx) return null;

  const bgDark = '#020617';
  const bgCard = '#0f172a';
  const textLight = '#f8fafc';
  const textDim = '#94a3b8';
  
  let accent = '#10b981'; // Emerald
  let accentDim = 'rgba(16, 185, 129, 0.2)';
  let statusLabel = "PAID EARLY";

  if (timeliness === 'late') {
      accent = '#f43f5e'; // Rose
      accentDim = 'rgba(244, 63, 94, 0.2)';
      statusLabel = "PAID LATE";
  } else if (timeliness === 'ontime') {
      accent = '#fbbf24'; // Amber
      accentDim = 'rgba(251, 191, 36, 0.2)';
      statusLabel = "PAID ON TIME";
  }

  drawBackground(ctx, size, bgDark);
  drawFromLabel(ctx, fromName);

  // MAIN CARD
  const cardMargin = 100;
  const cardWidth = size - (cardMargin * 2);
  const cardHeight = size - (cardMargin * 2) + 20;
  const cardRadius = 40;

  ctx.shadowColor = accent;
  ctx.shadowBlur = 80;
  ctx.shadowOffsetY = 20;
  ctx.fillStyle = bgCard;
  roundRect(ctx, cardMargin, cardMargin, cardWidth, cardHeight, cardRadius);
  ctx.fill();
  
  // CRITICAL FIX: Reset shadow properties to prevent ghosting text
  ctx.shadowBlur = 0;
  ctx.shadowOffsetY = 0;
  ctx.shadowOffsetX = 0;
  ctx.shadowColor = 'transparent';

  ctx.lineWidth = 4;
  ctx.strokeStyle = '#334155';
  ctx.stroke();

  // Accent Line
  ctx.beginPath();
  ctx.moveTo(cardMargin + cardRadius, cardMargin);
  ctx.lineTo(cardMargin + cardWidth - cardRadius, cardMargin);
  ctx.lineWidth = 12;
  ctx.strokeStyle = accent;
  ctx.stroke();

  // Header
  ctx.fillStyle = textDim;
  ctx.font = 'bold 32px "Inter", sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'top';
  ctx.fillText('PAYMENT RECEIVED', size / 2, cardMargin + 60);

  // Amount
  ctx.fillStyle = textLight;
  ctx.font = 'bold 140px "Inter", sans-serif'; 
  ctx.textBaseline = 'middle';
  const amountStr = `${currency}${Math.round(amountPaid).toLocaleString('en-IN')}`;
  ctx.fillText(amountStr, size / 2, cardMargin + 200);

  // Status Pill
  ctx.font = 'bold 36px "Inter", sans-serif';
  const textWidth = ctx.measureText(statusLabel).width;
  const pillPadding = 40;
  const pillWidth = textWidth + (pillPadding * 2);
  const pillHeight = 70;
  const pillX = (size - pillWidth) / 2;
  const pillY = cardMargin + 300;

  ctx.fillStyle = accentDim;
  roundRect(ctx, pillX, pillY, pillWidth, pillHeight, 20);
  ctx.fill();
  ctx.strokeStyle = accent;
  ctx.lineWidth = 3;
  ctx.stroke();
  ctx.fillStyle = accent;
  ctx.fillText(statusLabel, size / 2, pillY + pillHeight/2 + 2); 

  // Message
  ctx.fillStyle = '#e2e8f0';
  ctx.font = '500 42px "Inter", sans-serif';
  const messageY = pillY + pillHeight + 80;
  wrapText(ctx, customMessage, size / 2, messageY, cardWidth - 80, 60);

  // Footer Stats
  const bottomSectionY = cardMargin + cardHeight - 160;
  drawFooterNameAndId(ctx, size, bottomSectionY - 20, "RECEIVED FROM:", payerName, profileId, accent);

  // Balance info (Small below name)
  const balanceY = bottomSectionY + 130;
  if (remainingBalance > 0) {
      ctx.fillStyle = '#e2e8f0'; // Brighter for better visibility
      ctx.font = 'bold 32px "Inter", sans-serif'; // Larger for readability
      ctx.fillText(`REMAINING NET: ${currency}${remainingBalance.toLocaleString('en-IN')}`, size / 2, balanceY);
  } else {
      ctx.fillStyle = '#10b981'; // Green
      ctx.font = 'bold 32px "Inter", sans-serif'; // Larger
      ctx.fillText(`ALL SETTLED!`, size / 2, balanceY);
  }

  drawBranding(ctx, size);

  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      if (blob) {
        const file = new File([blob], `Receipt_${payerName.replace(/\s/g, '_')}.png`, { type: 'image/png' });
        resolve(file);
      } else {
        resolve(null);
      }
    }, 'image/png');
  });
};

export const generateLoanCard = async (
  fromName: string,
  borrowerName: string,
  profileId: string,
  amount: number,
  currency: string,
  startDate: string,
  returnDate: string,
  interestRate: number,
  interestType: string,
  interestFree: boolean,
  notes: string
): Promise<File | null> => {
  const size = 1080;
  const { canvas, ctx } = setupCanvas(size);
  if (!ctx) return null;

  const bgDark = '#020617';
  const bgCard = '#0f172a';
  const textLight = '#f8fafc';
  const textDim = '#94a3b8';
  
  // Blue/Cyan theme for Loan Contracts
  const accent = '#3b82f6'; 
  const accentDim = 'rgba(59, 130, 246, 0.15)';

  drawBackground(ctx, size, bgDark);
  drawFromLabel(ctx, fromName);

  // MAIN CARD
  const cardMargin = 100;
  const cardWidth = size - (cardMargin * 2);
  const cardHeight = size - (cardMargin * 2) + 20;
  const cardRadius = 40;

  ctx.shadowColor = accent;
  ctx.shadowBlur = 80;
  ctx.shadowOffsetY = 20;
  ctx.fillStyle = bgCard;
  roundRect(ctx, cardMargin, cardMargin, cardWidth, cardHeight, cardRadius);
  ctx.fill();
  
  // CRITICAL FIX: Reset shadow properties to prevent ghosting text
  ctx.shadowBlur = 0;
  ctx.shadowOffsetY = 0;
  ctx.shadowOffsetX = 0;
  ctx.shadowColor = 'transparent';

  ctx.lineWidth = 4;
  ctx.strokeStyle = '#334155';
  ctx.stroke();

  // Accent Line
  ctx.beginPath();
  ctx.moveTo(cardMargin + cardRadius, cardMargin);
  ctx.lineTo(cardMargin + cardWidth - cardRadius, cardMargin);
  ctx.lineWidth = 12;
  ctx.strokeStyle = accent;
  ctx.stroke();

  // Header
  ctx.fillStyle = textDim;
  ctx.font = 'bold 32px "Inter", sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'top';
  ctx.fillText('LOAN AGREEMENT', size / 2, cardMargin + 60);

  // Amount
  ctx.fillStyle = textLight;
  ctx.font = 'bold 140px "Inter", sans-serif'; 
  ctx.textBaseline = 'middle';
  const amountStr = `${currency}${Math.round(amount).toLocaleString('en-IN')}`;
  ctx.fillText(amountStr, size / 2, cardMargin + 200);

  // Details Section (Table style)
  let detailsY = cardMargin + 320;
  const lineHeight = 60;
  
  ctx.font = '500 28px "Inter", sans-serif';
  
  const drawRow = (label: string, value: string, isHighlight = false) => {
     ctx.textAlign = 'left';
     ctx.fillStyle = '#64748b';
     ctx.fillText(label, cardMargin + 60, detailsY);
     
     ctx.textAlign = 'right';
     ctx.fillStyle = isHighlight ? accent : '#e2e8f0';
     ctx.fillText(value, cardMargin + cardWidth - 60, detailsY);
     
     // Line
     ctx.beginPath();
     ctx.strokeStyle = '#1e293b';
     ctx.lineWidth = 2;
     ctx.moveTo(cardMargin + 60, detailsY + 20);
     ctx.lineTo(cardMargin + cardWidth - 60, detailsY + 20);
     ctx.stroke();

     detailsY += lineHeight + 20;
  };

  const fmtDate = (d: string) => new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });

  drawRow("Date Given", fmtDate(startDate));
  drawRow("Due Date", fmtDate(returnDate));
  
  if (interestRate > 0) {
      const typeStr = interestType === 'none' ? 'Fixed (Flat)' : interestType.charAt(0).toUpperCase() + interestType.slice(1);
      drawRow("Interest", `${interestRate}% ${typeStr}`);
  } else {
      drawRow("Interest", "None (0%)");
  }

  if (interestFree && interestRate > 0) {
      ctx.textAlign = 'center';
      ctx.fillStyle = '#10b981'; // Green for good news
      ctx.font = 'bold 24px "Inter", sans-serif';
      ctx.fillText("✓ No interest if paid by due date", size / 2, detailsY + 10);
      detailsY += 60;
  }
  
  if (notes) {
      ctx.textAlign = 'center';
      ctx.fillStyle = textDim;
      ctx.font = 'italic 24px "Inter", sans-serif';
      // Truncate notes if too long
      const displayNote = notes.length > 40 ? notes.substring(0, 37) + "..." : notes;
      ctx.fillText(`"${displayNote}"`, size / 2, detailsY + 10);
  }

  // Footer
  const bottomSectionY = cardMargin + cardHeight - 160;
  drawFooterNameAndId(ctx, size, bottomSectionY - 20, "AGREEMENT WITH:", borrowerName, profileId, accent);

  drawBranding(ctx, size);

  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      if (blob) {
        const file = new File([blob], `Loan_Contract_${borrowerName.replace(/\s/g, '_')}.png`, { type: 'image/png' });
        resolve(file);
      } else {
        resolve(null);
      }
    }, 'image/png');
  });
};

export const generateUPIQrCard = async (
  qrUrl: string,
  userName: string,
  amount: string,
  vpa: string
): Promise<File | null> => {
  const size = 1080;
  const { canvas, ctx } = setupCanvas(size);
  if (!ctx) return null;

  const bgDark = '#020617';
  const bgCard = '#0f172a';
  const textLight = '#f8fafc';
  
  const accent = '#10b981'; // Emerald for money

  // Draw Background
  drawBackground(ctx, size, bgDark);
  
  // Card Container
  const cardMargin = 100;
  const cardWidth = size - (cardMargin * 2);
  const cardHeight = size - (cardMargin * 2);
  const cardRadius = 40;

  ctx.shadowColor = accent;
  ctx.shadowBlur = 60;
  ctx.fillStyle = bgCard;
  roundRect(ctx, cardMargin, cardMargin, cardWidth, cardHeight, cardRadius);
  ctx.fill();
  
  ctx.shadowBlur = 0; // Reset shadow

  ctx.strokeStyle = '#334155';
  ctx.lineWidth = 4;
  ctx.stroke();

  // Load QR Image
  try {
      const qrImg = await loadImage(qrUrl);
      
      // Draw QR Code centered
      const qrSize = 500;
      const qrX = (size - qrSize) / 2;
      const qrY = cardMargin + 80;
      
      // White background for QR to ensure readability
      ctx.fillStyle = '#ffffff';
      roundRect(ctx, qrX - 20, qrY - 20, qrSize + 40, qrSize + 40, 20);
      ctx.fill();
      
      ctx.drawImage(qrImg, qrX, qrY, qrSize, qrSize);
      
  } catch (e) {
      console.error("Failed to load QR image for canvas", e);
      return null;
  }

  // Text Below
  ctx.textAlign = 'center';
  
  // Amount
  ctx.fillStyle = accent;
  ctx.font = 'bold 80px "Inter", sans-serif';
  ctx.fillText(`₹${amount}`, size / 2, cardMargin + 680);

  // "Scan to pay..."
  ctx.fillStyle = '#94a3b8'; // Slate 400
  ctx.font = '500 32px "Inter", sans-serif';
  ctx.fillText("SCAN TO PAY YOUR LOAN TO", size / 2, cardMargin + 760);

  // User Name
  ctx.fillStyle = textLight;
  ctx.font = 'bold 60px "Inter", sans-serif';
  ctx.fillText(userName.toUpperCase(), size / 2, cardMargin + 830);
  
  // VPA
  ctx.fillStyle = '#cbd5e1'; // Slate 300 - High contrast against #020617
  ctx.font = 'bold 34px "Courier New", monospace';
  ctx.shadowColor = '#000000';
  ctx.shadowBlur = 4;
  ctx.fillText(vpa, size / 2, cardMargin + 900);
  ctx.shadowBlur = 0; // Reset

  drawBranding(ctx, size);

  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      if (blob) {
        const file = new File([blob], `UPI_Payment_${userName.replace(/\s/g, '_')}.png`, { type: 'image/png' });
        resolve(file);
      } else {
        resolve(null);
      }
    }, 'image/png');
  });
};
